export const LISTAR_EQUIPOS = 'LISTAR_EQUIPOS';
export const DETALLE_EQUIPO = 'DETALLE_EQUIPO';
export const AGREGAR_EQUIPO = 'AGREGAR_EQUIPO';
export const AGREGAR_INTEGRANTE = 'AGREGAR_INTEGRANTE';
export const ELIMINAR_INTEGRANTE = 'ELIMINAR_INTEGRANTE';
export const ERROR = 'ERROR';
