let id = 1;

export default [{"id":2,"tipo":"Carreteras","denominacion":"CONTRATO DE CONCESIÓN DEL TRAMO ANCÓN - HUACHO - PATIVILCA DE LA CARRETERA PANAMERICANA NORTE (RED VIAL 5)","codigo":null,"snip":null},
    {"id":3,"tipo":"Carreteras","denominacion":"CONTRATO DE CONCESIÓN PARA LA CONSTRUCCIÓN Y EXPLOTACIÓN DEL TRAMO VIAL PUENTE PUCUSANA - CERRO AZUL - ICA DE LA CARRETERA PANAMERICANA SUR","codigo":null,"snip":null},
    {"id":4,"tipo":"Carreteras","denominacion":"CONCESIÓN DEL TRAMO VIAL URCOS - INAMBARI DEL PROYECTO CORREDOR VIAL INTEROCEÁNICO SUR, PERÚ – BRASIL (TRAMO 2: URCOS - INAMBARI)","codigo":null,"snip":null},
    {"id":5,"tipo":"Carreteras","denominacion":"CONTRATO DE CONCESIÓN DE LAS OBRAS Y EL MANTENIMIENTO DE LOS TRAMOS VIALES DEL EJE MULTIMODAL DEL AMAZONAS NORTE DEL","codigo":null,"snip":null},
    {"id":6,"tipo":"Carreteras","denominacion":"CONCESIÓN DEL TRAMO VIAL INAMBARI - IÑAPARI DEL PROYECTO CORREDOR VIAL INTEROCEÁNICO SUR, PERÚ – BRASIL (TRAMO 3: INAMBARI - IÑAPARI)","codigo":null,"snip":null},
    {"id":7,"tipo":"Carreteras","denominacion":"CONCESIÓN DEL TRAMO VIAL INAMBARI - AZÁNGARO DEL PROYECTO CORREDOR VIAL INTEROCEÁNICO SUR, PERÚ - BRASIL TRAMO 4: INAMBARI - AZÁNGARO","codigo":null,"snip":null},
    {"id":8,"tipo":"Carreteras","denominacion":"CONTRATO DE CONCESION DE LAS OBRAS Y EL MANTENIMIENTO DE LOS TRAMOS VIALES: EMPALME 1B BUENOS AIRES- CANCHAQUE","codigo":null,"snip":245326},
    {"id":9,"tipo":"Carreteras","denominacion":"TRAMOS VIALES DE LA RED VIAL N° 4 PATIVILCA - DV SALAVERRY","codigo":null,"snip":null},
    {"id":10,"tipo":"Carreteras","denominacion":"CONCESIÓN DESVÍO QUILCA - DESVÍO AREQUIPA (REPARTICIÓN) - DESVÍO MATARANI - DESVÍO MOQUEGUA - DESVÍO ILO - TACNA - LA CONCORDIA","codigo":null,"snip":null},
    {"id":11,"tipo":"Carreteras","denominacion":"CONTRATO DE CONCESIÓN DEL TRAMO 2 DE IIRSA CENTRO: PUENTE RICARDO PALMA - LA OROYA – HUANCAYO y LA OROYA – DV CERRO DE PASCO","codigo":null,"snip":null},
    {"id":12,"tipo":"Carreteras","denominacion":"IIRSA SUR TRAMO 1 Corredor Vial Interoceánico Sur Perú – Brasil","codigo":null,"snip":null},
    {"id":13,"tipo":"Carreteras","denominacion":"IIRSA SUR TRAMO 5 Corredor Vial Interoceánico Sur Perú – Brasil","codigo":null,"snip":null},
    {"id":14,"tipo":"Carreteras","denominacion":"CONTRATO DE CONCESIÓN PARA LA CONSTRUCCIÓN, CONSERVACIÓN Y EXPLOTACIÓN DEL TRAMO VIAL NUEVO MOCUPE - CAYALTÍ - OYOTÚN","codigo":null,"snip":null},
    {"id":15,"tipo":"Carreteras","denominacion":"CONTRATO DE CONCESIÓN PARA LA CONSTRUCCION, CONSERVACIÓN Y OPERACIÓN DEL TRAMO VIAL ÓVALO CHANCAY / DV. VARIANTE PASAMYO - HUARAL - ACOS","codigo":null,"snip":null},
    {"id":16,"tipo":"Carreteras","denominacion":"CARRETERA LONGITUDINAL DE LA SIERRA TRAMO 2: CIUDAD DE DIOS - CAJAMARCA - CHIPLE, CAJAMARCA - TRUJILLO Y DV. CHILETE - EMP. PE-3N.","codigo":null,"snip":null},
    {"id":17,"tipo":"Puertos","denominacion":"TERMINAL PORTUARIO MATARANI","codigo":null,"snip":null},
    {"id":18,"tipo":"Puertos","denominacion":"Nuevo Terminal de Contenedores en el Terminal Portuario del Callao - Zona Sur","codigo":null,"snip":null},
    {"id":19,"tipo":"Puertos","denominacion":"TERMINAL PORTUARIO DE PAITA","codigo":null,"snip":null},
    {"id":20,"tipo":"Puertos","denominacion":"TERMINAL DE EMBARQUE DE CONCENTRADOS DE MINERALES EN EL TERMINAL PORTUARIO DEL CALLAO","codigo":null,"snip":null},
    {"id":21,"tipo":"Puertos","denominacion":"TERMINAL NORTE MULTIPROPÓSITO EN EL TERMINAL PORTUARIO DEL CALLAO","codigo":null,"snip":null},
    {"id":22,"tipo":"Puertos","denominacion":"TERMINAL PORTUARIO GENERAL SAN MARTIN - PISCO","codigo":null,"snip":null},
    {"id":23,"tipo":"Puertos","denominacion":"Terminal Portuario Multipropósito de Salaverry","codigo":null,"snip":null},
    {"id":24,"tipo":"Puertos","denominacion":"Nuevo Terminal Portuario de Yurimaguas - Nueva Reforma","codigo":2115734,"snip":33141},
    {"id":25,"tipo":"Puertos","denominacion":"Hidrovía Amazónica","codigo":2086551,"snip":102740},
    {"id":26,"tipo":"Ferroviarios","denominacion":"Ferrocarril del Centro","codigo":null,"snip":null},
    {"id":27,"tipo":"Ferroviarios","denominacion":"Ferrocarril del Sur y Sur Oriente","codigo":null,"snip":null},
    {"id":28,"tipo":"Ferroviarios","denominacion":"Contrato de Concesión del Proyecto Especial Sistema Eléctrico de Transporte Masivo de Lima y Callao, Línea Nº 1, Villa El Salvador - Av. Grau - San Juan de Lurigancho","codigo":2257430,"snip":314626},
    {"id":29,"tipo":"Ferroviarios","denominacion":"Línea 2 y Ramal Av. Faucett - Av. Gambetta de la Red Básica del Metro de Lima y Callao\n","codigo":2233850,"snip":239307},
    {"id":30,"tipo":"Aeropuertos","denominacion":"Contrato de Concesión del Primer Grupo de Aeropuertos de Provincia de la República del Perú","codigo":null,"snip":null},
    {"id":31,"tipo":"Aeropuertos","denominacion":"Contrato de Concesión del Segundo Grupo de Aeropuertos de Provincia de la República del Perú","codigo":null,"snip":null},
    {"id":32,"tipo":"Aeropuertos","denominacion":"Contrato de Concesión para la construcción, mejora, conservación y explotación del Aeropuerto Internacional","codigo":null,"snip":null}]
