export var tipovias_global=[{"tipovia":"AL"}, {"tipovia":"AV"},
    {"tipovia":"BO"},
    {"tipovia":"CA"},
    {"tipovia":"CL"},
    {"tipovia":"JR"},
    {"tipovia":"PJ"},
    {"tipovia":"PL"},
    {"tipovia":"PQ"},
    {"tipovia":"PR"},
    {"tipovia":"PS"},
    {"tipovia":"PSJ"}];

export var tipourbanizacion_global=[{"tipourbanizacion":"AGR"},
    {"tipourbanizacion":"AH"},
    {"tipourbanizacion":"ASOC"},
    {"tipourbanizacion":"BARRIO"},
    {"tipourbanizacion":"CH"},
    {"tipourbanizacion":"COND"},
    {"tipourbanizacion":"COOP"},
    {"tipourbanizacion":"CP"},
    {"tipourbanizacion":"FUNDO"},
    {"tipourbanizacion":"LOT"},
    {"tipourbanizacion":"POBLADO"},
    {"tipourbanizacion":"PPJJ"},
    {"tipourbanizacion":"RES"},
    {"tipourbanizacion":"URB"},
    {"tipourbanizacion":"UV"},
    {"tipourbanizacion":"VILLA"}];